  json.practice thought.practice_id
  json.thought_id thought.id
  json.content thought.content
  json.sadness thought.sadness
  json.joy thought.joy
  json.fear thought.fear
  json.disgust thought.disgust
  json.anger thought.anger
  json.red @thought.red
  json.green @thought.green
  json.blue @thought.blue
  json.x_value @thought.x_value
  json.y_value @thought.y_value
